"""empty message

Revision ID: 0a03fdb90e78
Revises: 9079aeb940e6
Create Date: 2024-04-10 18:31:18.258471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a03fdb90e78'
down_revision = '9079aeb940e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('ddd')
        batch_op.drop_column('ddddd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ddddd', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('ddd', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
